-- ============================================================
-- DEVELOPMENT SEED DATA
-- ============================================================
-- Intentionally empty of sample reading data.
--
-- The previous fabricated fixtures (a "Dev Reader" device, the books
-- "Leviathan Wakes" / "Project Hail Mary", their highlights/notes, and a sample
-- book transfer) were removed: dev now works against REAL data synced from an
-- actual device, so fake highlights only added noise. A `db reset` therefore
-- starts clean — real books/highlights appear once a paired device syncs.
--
-- The local dev login (test@example.com) is created by the gitignored
-- supabase/seed.local.sql, which runs before this file (see config.toml
-- [db.seed].sql_paths). Add per-developer local fixtures there if needed.
